adlarge_fixtures_documentation:
  title: Documentation auto
  enableAutoDocumentation: true
  configEntities:
    Product:
      - id
      - name
      - owner
      - tags
    Customer:
      - firstname
      - lastname
      - email